stages:
    - build
    - prod

variables:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

before_script:
  - docker login -u $NEXUS_REGISTRY_USER -p $NEXUS_REGISTRY_PASSWD registry.mplab.io
  - mkdir -p fastapi/sessions
  - echo "Preserving sessions directory"

cache:
  paths:
    - fastapi/sessions/

build:
  allow_failure: true
  stage: build
  image: docker
  only:
  - main
  variables:
    CONTAINER_IMAGE: registry.mplab.io/eliment-web:${CI_COMMIT_SHORT_SHA}
    CONTAINER_IMAGE_LATEST: registry.mplab.io/eliment-web:latest
  script:
  - docker build -t ${CONTAINER_IMAGE} .
  - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
  - docker push ${CONTAINER_IMAGE_LATEST}
  - docker system prune -f -a

build:eliment-cli:
  #allow_failure: true
  stage: build
  image: docker
  only:
    - main
  variables:
    CONTAINER_IMAGE: registry.mplab.io/eliment-cli:${CI_COMMIT_SHORT_SHA}
    CONTAINER_IMAGE_LATEST: registry.mplab.io/eliment-cli:latest
  script:
    - docker build -f Dockerfile -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE_LATEST}


prod:
  stage: prod
  tags: [app-ea]
  when: manual
  image:
    name: docker/compose
    entrypoint: ["/bin/sh", "-c"]
  script:
    - docker network create web_network || true
    - docker compose -f docker-compose.yml down
    - docker compose -f docker-compose.yml -p eliment-web down --timeout 10
    - docker compose -f docker-compose.yml  pull eliment-web
    - docker compose -f docker-compose.yml  up -d eliment-web
    - docker image prune -a -f
    - docker builder prune -f
    - docker image prune -a -f
