services:

  appseed-app:
    container_name: appseed_app
    #build: .
    image: registry.mplab.io/eliment-web:latest
    restart: always
    env_file: .env
    networks:
      - web_network
    volumes:
      - /mnt/media/images:/app/apps/media/images
    ports:
      - "80:80"

networks:
  web_network:
       external: true
       name: web_network
