services:
  neuro-backend:
    container_name: neuro-backend
    image: registry.mplab.io/neuro-backend:latest
    restart: always
    env_file: .env-dev
    volumes:
      - /mnt/media/images:/app/apps/media/images
    # depends_on:
    #   - fastapi-app
    ports:
      - "80:80"
    command: gunicorn --config gunicorn-cfg.py core.wsgi --workers 12 --threads 12 --timeout 300 --graceful-timeout 300 --max-requests 1000 --max-requests-jitter 50


  eliment-cli:
    container_name: eliment-cli
    image: registry.mplab.io/neuro-backend:latest
    restart: always
    env_file: .env-dev

  eliment-cli-kafka-message-reply:
    container_name: eliment-cli-kafka-message-reply
    image: registry.mplab.io/neuro-backend:latest
    restart: always
    env_file: .env-dev
    command: python manage.py reply_telegram_messages